version: "3.8"

services:
  nestapp:
    build: ./proyecto-pf
    ports:
      - "3000:3000"
    env_file:
      - ./proyecto-pf/.env
    depends_on:
      - postgresdb

  postgresdb:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./proyecto-pf/.env

volumes:
  pgdata:
