name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify package.json presence
        run: |
          ls -la ./proyecto-pf
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./proyecto-pf
          file: ./proyecto-pf/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deppf:latest
